apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  # clusterIP: None
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - name: tcp
      protocol: TCP
      targetPort: 3306
      port: 3306
