name: github action demo

on:
  push:
    branches: [master, main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [master, main]

jobs:
  build:
    # Name the Job
    name: github action demo
    # Set the agent to run on
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      
      # - name: Build Image
      #   run: |
      #     docker build ./demo -t demo-app:1.0.1 

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: shshrivastava7 #${{ secrets.DOCKER_HUB_USERNAME }}
          password: dckr_pat_FAMs0QpEid-LIoPNpPYF5H3714s #${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          # file: demo/
          push: true
          tags: shshrivastava7/demo-image:latest
          