name: github action demo

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    # Name the Job
    name: github action demo
    # Set the agent to run on
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Build and push
        # uses: docker/build-push-action@v3
        run: |
          docker build -f ./demo/Dockerfile -t shshrivastava7/demo-app:1.0.1 ./demo
          docker tag shshrivastava7/app-demo:1.0.1 shshrivastava7/demo-image:latest
          docker push shshrivastava7/demo-image:latest
        # docker push shshrivastava7/demo-app:1.0.1
        # with:
        #   context: ./demo
        #   file: ./demo/Dockerfile
        #   push: true
        #   tags: shshrivastava7/demo-image:latest
    