name: github action demo
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
jobs:
  build:
    name: github action demo
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        run: |
          docker build -f ./demo/Dockerfile -t shshrivastava7/demo-image:latest ./demo
          docker tag shshrivastava7/demo-image:latest shshrivastava7/demo-image:latest
          docker push shshrivastava7/demo-image:latest
