
name: github action demo

on:
  push:
    branches: [master, main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [master, main]

jobs:
  build:
    # Name the Job
    name: github action demo
    # Set the agent to run on
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      
      - name: Build Image
        used: action/checkout@v3
        run:  |
          docker build -t demo-app:1.0.1
          echo "docker image created"